# Site settings
title: 刚子
baseurl: ""
url: "http://liaogang.github.io"

# Build settings
markdown: kramdown
permalink: pretty

#　禁用自定义插件
safe: true

# default values
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values: 
      layout: "post_center"
      post_width: "702"
      image_server_base: "https://coding.net/u/liaogang123/p/ImageServer/git/raw/master/"
